language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/btcsuite
    - $GOPATH/src/github.com/golang

go:
  - "1.12.x"

sudo: required

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GO111MODULE=on
  - go test -v
