language: go
cache:
  directories:
    - ~/bitcoin/bitcoin-0.19.1/bin
    - $DOWNLOAD_CACHE
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/btcsuite
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/github.com/grpc-ecosystem
    - $GOPATH/src/gopkg.in/alecthomas
    - $GOPATH/src/google.golang.org

# Remove Travis' default flag --depth=50 from the git clone command to make sure
# we have the whole git history, including the commit we lint against.
git:
  depth: false

go:
  - "1.14.x"

env:
  global:
    - GOCACHE=$HOME/.go-build
    - DOWNLOAD_CACHE=$HOME/download_cache

sudo: required

jobs:
  include:
    - stage: Integration Test
      name: Btcd Integration
      script:
        - make itest

    - name: Bitcoind Integration
      script:
        - bash ./scripts/install_bitcoind.sh
        - make itest backend=bitcoind

    - name: Neutrino Integration
      script:
        - make itest backend=neutrino

    - name: Btcd Integration ARM
      script:
        - GOARM=7 GOARCH=arm GOOS=linux CGO_ENABLED=0 make btcd build-itest
        - file lnd-itest
        - GOARM=7 GOARCH=arm GOOS=linux CGO_ENABLED=0 make itest-only
      arch: arm64

after_script:
  - LOG_FILES=./lntest/itest/*.log
  - echo "Uploading to termbin.com..." && find $LOG_FILES | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..." && tar -zcvO $LOG_FILES | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
