language: go
go:
  - 1.8.5
  - 1.9.2
sudo: false
install:
  - add-apt-repository -y ppa:bitcoin/bitcoin
  - apt-update
  - apt-get -y install bitcoind
  - GLIDE_TAG=v0.12.3
  - GLIDE_DOWNLOAD="https://github.com/Masterminds/glide/releases/download/$GLIDE_TAG/glide-$GLIDE_TAG-linux-amd64.tar.gz"
  - curl -L $GLIDE_DOWNLOAD | tar -xvz
  - export PATH=$PATH:$PWD/linux-amd64/
  - BTCD_VERSION=$(cat glide.yaml | grep -A1 btcd | tail -n1 | awk '{ print $2}')
  - mkdir -p $GOPATH/src/github.com/roasbeef/
  - pushd $GOPATH/src/github.com/roasbeef/
  - git clone https://github.com/roasbeef/btcd
  - pushd btcd
  - git checkout $BTCD_VERSION
  - glide install
  - go install . ./cmd/...
  - popd
  - popd
env:
  global:
    - LOGS=true
  matrix:
    - RACE=false
    - RACE=true
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./gotest.sh
after_script:
  - find *.log | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
