language: go
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/btcsuite
    - $GOPATH/src/github.com/golang
    - $GOPATH/src/github.com/grpc-ecosystem
    - $GOPATH/src/gopkg.in/alecthomas
    - $GOPATH/src/google.golang.org

# Remove Travis' default flag --depth=50 from the git clone command to make sure
# we have the whole git history, including the commit we lint against.
git:
  depth: false

go:
  # If you change this value, please change it in the following files as well:
  # /Dockerfile
  # /dev.Dockerfile
  # /make/builder.Dockerfile
  # /.github/workflows/main.yml
  # /.github/workflows/release.yml
  - "1.17.x"

env:
  global:
    - GOCACHE=$HOME/.go-build
    - BITCOIN_VERSION="22.0"

sudo: required

jobs:
  include:
    - stage: Sanity Check
      name: Lint and compile
      script:
        # Step 1: Make sure no diff is produced when compiling with the correct
        # version.
        - make rpc-check

        # Step 2: Make sure the unit tests compile, but don't run them. They run
        # in a GitHub Workflow.
        - make unit pkg=... case=_NONE_

        # Step 3: Lint go code. Invoke GC more often to reduce memory usage.
        - GOGC=30 make lint

    - stage: Integration Test
      name: Bitcoind Integration ARM
      script:
        - bash ./scripts/install_bitcoind.sh
        - GOARM=7 GOARCH=arm GOOS=linux make itest-parallel backend=bitcoind tranches=3 parallel=3
      arch: arm64
      services:
        - docker

after_failure:
  - |-
    LOG_FILES=$(find ./lntest/itest -name '*.log')
    echo "Uploading to termbin.com..." && for f in $LOG_FILES; do echo -n $f; cat $f | nc termbin.com 9999 | xargs -r0 printf ' uploaded to %s'; done
    echo "Uploading to file.io..." && tar -zcvO $LOG_FILES | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
